# ---------------------------------------------------------
#                 _                 _     _       
#                | |               | |   (_)      
#             ___| |_ __ _ _ __ ___| |__  _ _ __  
#            / __| __/ _` | '__/ __| '_ \| | '_ \ 
#            \__ \ || (_| | |  \__ \ | | | | |_) |
#            |___/\__\__,_|_|  |___/_| |_|_| .__/ 
#                                          | |    
#                                          |_|
# --------------------------------------------------------- 
# DOCS --> https://starship.rs/config/

# Change terminal prompt character 

[character]
success_symbol = '[](bold green) '
error_symbol = '[](bold red) '

[directory]
read_only = ' '